spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

# auto--ddl  none 은 테이블을 드롭하지 않음. drop 하고싶을 때는 create 작성할것

    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace


